from hybrid_retriever import HybridRetriever
from prompt_builder import PromptBuilder
from llm_client import LLMClient
from sql_validator import SQLValidator


class SQLAutoCorrector:
    """
    Automatic SQL correction pipeline.

    Pipeline:
        Generated SQL
            ↓
        SQL Validator
            ↓
        If invalid → LLM correction
            ↓
        SQL Validator
            ↓
        Valid SQL / Rejected SQL

    The SQL is NEVER executed here.
    """

    def __init__(
        self,
        llm_client,
        validator,
        max_attempts=3
    ):
        self.max_attempts = max_attempts
        self.llm_client = llm_client
        self.validator = validator

    # ---------------------------------------------------------
    # Build correction prompt
    # ---------------------------------------------------------

    def build_correction_prompt(self, sql, error, question, context):
        """
        Build a prompt asking the LLM to correct an invalid SQL query.
        """

        return f"""
    You are an expert SQL assistant specialized in TPC-DS.

    The SQL query generated by the LLM failed validation.

    IMPORTANT RULES:

    1. Return ONLY a SELECT query.
    2. Use ONLY tables and columns provided in the context.
    3. NEVER invent a table.
    4. NEVER invent a column.
    5. Do NOT use tables or columns from general knowledge.
    6. Correct the SQL according to the validator error.
    7. Preserve the original business meaning of the question.
    8. Respect the KPI definitions.
    9. Respect the business rules.
    10. Do not replace a business measure with another column
        just because that column exists in the schema.
    11. Do not execute the query.
    12. If the query cannot be corrected using the context,
        return exactly:
        ADDITIONAL_INFORMATION_REQUIRED

    ORIGINAL QUESTION:
    {question}

    RETRIEVED CONTEXT:
    {context}

    INVALID SQL:
    {sql}

    VALIDATOR ERROR:
    {error}

    Return ONLY the corrected SQL.
    """

    # ---------------------------------------------------------
    # Extract context from prompt
    # ---------------------------------------------------------

    def extract_context(self, prompt):
        """
        Extract the retrieved context from the original prompt.

        If the expected marker is not found, use the complete prompt.
        """

        if "RETRIEVED CONTEXT:" in prompt:

            context = prompt.split(
                "RETRIEVED CONTEXT:",
                1
            )[1]

            if "Generate SQL" in context:

                context = context.split(
                    "Generate SQL",
                    1
                )[0]

            return context.strip()

        return prompt

    # ---------------------------------------------------------
    # Correct SQL
    # ---------------------------------------------------------

    def correct(self, sql, question="", context=""):
        """
        Validate and automatically correct SQL.

        Returns:
            {
                "valid": bool,
                "sql": str or None,
                "reason": str,
                "attempts": int,
                "history": [...]
            }
        """

        if not sql:

            return {
                "valid": False,
                "sql": None,
                "reason": "No SQL query provided.",
                "attempts": 0,
                "history": []
            }

        current_sql = sql
        history = []

        for attempt in range(1, self.max_attempts + 1):

            print("\n" + "=" * 60)
            print(f"VALIDATION ATTEMPT {attempt}")
            print("=" * 60)

            # -------------------------------------------------
            # Validate current SQL
            # -------------------------------------------------

            validation = self.validator.validate(current_sql)

            print("SQL:")
            print(current_sql)

            print("\nVALID:", validation["valid"])
            print("REASON:", validation["reason"])

            # -------------------------------------------------
            # SQL is valid
            # -------------------------------------------------

            if validation["valid"]:

                print("\nSQL ACCEPTED.")

                return {
                    "valid": True,
                    "sql": current_sql,
                    "reason": validation["reason"],
                    "attempts": attempt,
                    "history": history,
                    "tables": validation.get("tables", []),
                    "columns": validation.get("columns", [])
                }

            # Save failed attempt
            history.append({
                "attempt": attempt,
                "sql": current_sql,
                "reason": validation["reason"]
            })

            # -------------------------------------------------
            # Maximum attempts reached
            # -------------------------------------------------

            if attempt >= self.max_attempts:

                print("\nMAXIMUM CORRECTION ATTEMPTS REACHED.")
                print("SQL REJECTED.")

                return {
                    "valid": False,
                    "sql": current_sql,
                    "reason": validation["reason"],
                    "attempts": attempt,
                    "history": history,
                    "tables": validation.get("tables", []),
                    "columns": validation.get("columns", [])
                }

            # -------------------------------------------------
            # Ask LLM to correct SQL
            # -------------------------------------------------

            correction_prompt = self.build_correction_prompt(
                sql=current_sql,
                error=validation["reason"],
                question=question,
                context=context
            )

            print("\nASKING LLM TO CORRECT SQL...")

            result = self.llm_client.generate_with_metadata(
                correction_prompt,
                temperature=0.0
            )

            if not result:

                return {
                    "valid": False,
                    "sql": current_sql,
                    "reason": "No response received from Ollama.",
                    "attempts": attempt,
                    "history": history
                }

            raw_response = result.get("response", "")

            print("\nRAW CORRECTION RESPONSE:")
            print(raw_response)

            # -------------------------------------------------
            # Extract corrected SQL
            # -------------------------------------------------

            corrected_sql = self.llm_client.extract_sql(
                raw_response
            )

            if not corrected_sql:

                return {
                    "valid": False,
                    "sql": current_sql,
                    "reason": (
                        "LLM did not return a valid SQL query "
                        "during correction."
                    ),
                    "attempts": attempt,
                    "history": history
                }

            print("\nCORRECTED SQL:")
            print(corrected_sql)

            current_sql = corrected_sql

        return {
            "valid": False,
            "sql": current_sql,
            "reason": "SQL correction failed.",
            "attempts": self.max_attempts,
            "history": history
        }


# ============================================================
# TEST
# ============================================================

def main():

    print("\n")
    print("=" * 80)
    print("TESTING SQL AUTO-CORRECTION")
    print("=" * 80)

    # ---------------------------------------------------------
    # 1. Initialize Hybrid Retriever
    # ---------------------------------------------------------

    print("\n[1] Initializing Hybrid Retriever...")

    retriever = HybridRetriever()
    retriever.initialize()

    # ---------------------------------------------------------
    # 2. Initialize Prompt Builder
    # ---------------------------------------------------------

    print("\n[2] Initializing Prompt Builder...")

    prompt_builder = PromptBuilder(
        retriever=retriever
    )

    # ---------------------------------------------------------
    # 3. Initialize LLM Client
    # ---------------------------------------------------------

    print("\n[3] Initializing LLM Client...")

    llm_client = LLMClient(
        prompt_builder=prompt_builder
    )

    # ---------------------------------------------------------
    # 4. Initialize SQL Validator
    # ---------------------------------------------------------

    print("\n[4] Initializing SQL Validator...")

    validator = SQLValidator()

    # ---------------------------------------------------------
    # 5. Initialize Auto Corrector
    # ---------------------------------------------------------

    print("\n[5] Initializing SQL Auto-Corrector...")

    corrector = SQLAutoCorrector(
        llm_client=llm_client,
        validator=validator,
        max_attempts=3
    )

    # ---------------------------------------------------------
    # Test question
    # ---------------------------------------------------------

    question = (
        "What is the total revenue generated "
        "by store sales?"
    )

    # ---------------------------------------------------------
    # Intentionally invalid SQL
    # ---------------------------------------------------------

    sql = """
SELECT SUM(price)
FROM store_sales;
"""

    # ---------------------------------------------------------
    # Retrieved business context
    # ---------------------------------------------------------

    context = """
Table: store_sales

Columns:
ss_sold_date_sk
ss_item_sk
ss_customer_sk
ss_quantity
ss_sales_price
ss_net_paid
ss_net_paid_inc_tax
ss_net_profit

KPI:
Total Store Sales
Formula: SUM(ss_net_paid)

Business rule:
Store sales revenue must be calculated
using ss_net_paid.
"""

    print("\n")
    print("=" * 80)
    print("AUTO-CORRECTION TEST")
    print("=" * 80)

    print("\nQUESTION:")
    print(question)

    print("\nINVALID SQL:")
    print(sql)

    # ---------------------------------------------------------
    # Run correction
    # ---------------------------------------------------------

    result = corrector.correct(
        sql=sql,
        question=question,
        context=context
    )

    # ---------------------------------------------------------
    # Final result
    # ---------------------------------------------------------

    print("\n")
    print("=" * 80)
    print("FINAL RESULT")
    print("=" * 80)

    print("VALID:", result["valid"])
    print("REASON:", result["reason"])
    print("ATTEMPTS:", result["attempts"])

    if result.get("sql"):

        print("\nFINAL SQL:")
        print(result["sql"])

    if result.get("tables"):

        print("\nTABLES:")
        print(result["tables"])

    if result.get("columns"):

        print("\nCOLUMNS:")
        print(result["columns"])

    if result.get("history"):

        print("\nCORRECTION HISTORY:")

        for item in result["history"]:

            print(
                f"\nAttempt {item['attempt']}:"
            )

            print("SQL:")
            print(item["sql"])

            print("Reason:")
            print(item["reason"])

if __name__ == "__main__":
    main()