import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

OUTPUT_DIR = PROJECT_ROOT / "business_docs"
OUTPUT_FILE = OUTPUT_DIR / "business_rules.json"

RULES = [

    {
        "title": "Store Sales Revenue",
        "description": "Revenue generated by physical stores must always be calculated using the net amount paid.",
        "tables": ["store_sales"],
        "columns": ["ss_net_paid"],
        "kpis": ["Total Store Sales", "Average Store Sales"],
        "keywords": [
            "sales",
            "store",
            "revenue",
            "turnover"
        ]
    },

    {
        "title": "Catalog Sales Revenue",
        "description": "Revenue generated from catalog orders must use the net paid amount.",
        "tables": ["catalog_sales"],
        "columns": ["cs_net_paid"],
        "kpis": ["Total Catalog Sales"],
        "keywords": [
            "catalog",
            "sales",
            "revenue"
        ]
    },

    {
        "title": "Web Sales Revenue",
        "description": "Revenue generated from online sales must use the net paid amount.",
        "tables": ["web_sales"],
        "columns": ["ws_net_paid"],
        "kpis": ["Total Web Sales"],
        "keywords": [
            "web",
            "online",
            "sales"
        ]
    },

    {
        "title": "Store Returns",
        "description": "Returned products in physical stores must be calculated using the return amount.",
        "tables": ["store_returns"],
        "columns": ["sr_return_amt"],
        "kpis": ["Total Store Returns"],
        "keywords": [
            "returns",
            "refund",
            "store"
        ]
    },

    {
        "title": "Catalog Returns",
        "description": "Returned catalog products must use the catalog return amount.",
        "tables": ["catalog_returns"],
        "columns": ["cr_return_amount"],
        "kpis": ["Total Catalog Returns"],
        "keywords": [
            "catalog",
            "returns"
        ]
    },

    {
        "title": "Web Returns",
        "description": "Returned web orders must use the web return amount.",
        "tables": ["web_returns"],
        "columns": ["wr_return_amt"],
        "kpis": ["Total Web Returns"],
        "keywords": [
            "web",
            "returns"
        ]
    },

    {
        "title": "Inventory Quantity",
        "description": "Inventory level is determined using the quantity currently on hand.",
        "tables": ["inventory"],
        "columns": ["inv_quantity_on_hand"],
        "kpis": ["Inventory Quantity"],
        "keywords": [
            "inventory",
            "stock",
            "quantity"
        ]
    },

    {
        "title": "Customer Counting",
        "description": "The number of customers must be calculated using the customer surrogate key.",
        "tables": ["customer"],
        "columns": ["c_customer_sk"],
        "kpis": ["Customer Count"],
        "keywords": [
            "customer",
            "count"
        ]
    },

    {
        "title": "Product Counting",
        "description": "Products are identified using the item surrogate key.",
        "tables": ["item"],
        "columns": ["i_item_sk"],
        "kpis": ["Product Count"],
        "keywords": [
            "product",
            "item"
        ]
    },

    {
        "title": "Promotion Analysis",
        "description": "Promotion analysis must use the promotion dimension.",
        "tables": ["promotion"],
        "columns": ["p_promo_sk"],
        "kpis": ["Promotion Count"],
        "keywords": [
            "promotion",
            "campaign"
        ]
    },

    {
        "title": "Warehouse Analysis",
        "description": "Warehouse analysis must use the warehouse dimension.",
        "tables": ["warehouse"],
        "columns": ["w_warehouse_sk"],
        "kpis": ["Warehouse Count"],
        "keywords": [
            "warehouse"
        ]
    },

    {
        "title": "Discount Analysis",
        "description": "Average discounts must be computed using the extended discount amount.",
        "tables": ["store_sales"],
        "columns": ["ss_ext_discount_amt"],
        "kpis": ["Average Discount"],
        "keywords": [
            "discount",
            "average"
        ]
    }

]


def build_rules():

    rules = []

    for idx, rule in enumerate(RULES, start=1):

        rules.append({

            "id": f"BR{idx:03d}",

            "title": rule["title"],

            "description": rule["description"],

            "tables": rule["tables"],

            "columns": rule["columns"],

            "related_kpis": rule["kpis"],

            "keywords": rule["keywords"]

        })

    return rules


def main():

    OUTPUT_DIR.mkdir(exist_ok=True)

    rules = build_rules()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:

        json.dump(
            rules,
            f,
            indent=4,
            ensure_ascii=False
        )

    print("=" * 60)
    print(f"Business Rules generated : {len(rules)}")
    print(f"Saved to : {OUTPUT_FILE}")
    print("=" * 60)


if __name__ == "__main__":
    main()