from hybrid_retriever import HybridRetriever


class PromptBuilder:
    """
    Prompt Builder

    Responsibilities
    ----------------
    1. Retrieve relevant documents
    2. Convert documents into readable context
    3. Build the final prompt for the LLM
    """

    def __init__(self):

        self.retriever = HybridRetriever()

        self.retriever.initialize()

    # ---------------------------------------------------------
    # Retrieve Context
    # ---------------------------------------------------------

    def retrieve_context(self, question, top_k=5):
        """
        Retrieve the most relevant documents.
        """

        return self.retriever.retrieve(
            query=question,
            top_k=top_k
        )

    # ---------------------------------------------------------
    # Format Context
    # ---------------------------------------------------------

    def format_context(self, documents):
        """
        Convert retrieved documents into plain text.
        """

        context = []

        for index, document in enumerate(documents, start=1):

            text = []

            text.append(f"Document {index}")
            text.append(f"Type : {document['type']}")
            text.append(f"Title : {document['title']}")

            if document["content"]:
                text.append(f"Description : {document['content']}")

            metadata = document.get("metadata", {})

            if metadata:

                text.append("Metadata:")

                for key, value in metadata.items():

                    text.append(f"- {key}: {value}")

            text.append("-" * 60)

            context.append("\n".join(text))

        return "\n\n".join(context)

    # ---------------------------------------------------------
    # Build Prompt
    # ---------------------------------------------------------

    def build_prompt(self, question, top_k=5):
        """
        Build the complete prompt.
        """

        documents = self.retrieve_context(
            question=question,
            top_k=top_k
        )

        context = self.format_context(documents)

        prompt = f"""
You are an expert SQL assistant.

Your task is to generate SQL queries.

Use ONLY the information provided in the context.

If the answer cannot be inferred from the context,
reply that additional information is required.

==================================================
CONTEXT
==================================================

{context}

==================================================
QUESTION
==================================================

{question}

==================================================
Instructions

- Use the business rules.
- Use the KPI definitions.
- Use the glossary.
- Use the retrieved evidence.
- Return only SQL when possible.

==================================================
SQL
==================================================
"""

        return prompt

    # ---------------------------------------------------------
    # Display Prompt
    # ---------------------------------------------------------

    def show_prompt(self, question, top_k=5):
        """
        Display the generated prompt.
        """

        prompt = self.build_prompt(
            question=question,
            top_k=top_k
        )

        print("\n")
        print("=" * 80)
        print("PROMPT SENT TO THE LLM")
        print("=" * 80)

        print(prompt)


# ============================================================
# Main
# ============================================================

def main():

    builder = PromptBuilder()

    question = "What is the total revenue generated by store sales?"

    builder.show_prompt(
        question=question,
        top_k=5
    )


if __name__ == "__main__":
    main()